GET  http://localhost:3000/api/v1/user/ HTTP/1.1
Content-Type: application/json

# https://blog.okazuki.jp/entry/2019/07/13/121021

###

POST http://localhost:3000/api/v1/user/ HTTP/1.1
Content-Type: application/json

{
    "name":"hoge",
    "screen_name":"pogepo",
    "bio":"Hello"
}

###

GET  http://localhost:3000/api/v1/user/5f95374668a98c71e9a02b7f HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:3000/api/v1/user/5f95374668a98c71e9a02b7f  HTTP/1.1
Content-Type: application/json

{
    "name":"hoge",
    "screen_name":"pogepo2",
    "bio":"Hello"
}

###
POST http://localhost:3000/api/v1/article/ HTTP/1.1
Content-Type: application/json

{
    "title": "saku",
    "text": "poi"
}
###
GET http://localhost:3000/api/v1/article/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/v1/article/5f963dfdf497a687701e931d HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3000/api/v1/article/5f963dfdf497a687701e931d HTTP/1.1
Content-Type: application/json
